import { StatusBar } from 'expo-status-bar';
import * as DocumentPicker from 'expo-document-picker';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';

declare const process: { env: Record<string, string | undefined> };
const API_URL = process.env.EXPO_PUBLIC_API_URL;
if (!API_URL) throw new Error('EXPO_PUBLIC_API_URL must be set');
type FileItem = { id:string; name:string; sizeBytes:string; mimeType:string; sha256:string };

export default function App() {
  const [token,setToken]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState('');
  const [files,setFiles]=useState<FileItem[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const call=useCallback(async(path:string,init:RequestInit={})=>{const response=await fetch(`${API_URL}${path}`,{...init,headers:{...(init.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})}});const body=await response.json();if(!response.ok)throw new Error(body.error);return body;},[token]);
  const load=useCallback(async()=>{if(!token)return;try{setFiles((await call('/items')).files)}catch(e){setMessage(e instanceof Error?e.message:'목록 오류')}},[call,token]);
  useEffect(()=>{void load()},[load]);
  const login=async()=>{setBusy(true);try{const result=await call('/auth/login',{method:'POST',body:JSON.stringify({username,password})});setToken(result.token)}catch(e){setMessage(e instanceof Error?e.message:'로그인 실패')}finally{setBusy(false)}};
  const upload=async()=>{const result=await DocumentPicker.getDocumentAsync({multiple:false,copyToCacheDirectory:false});if(result.canceled)return;const asset=result.assets[0];setBusy(true);try{const body=new FormData();body.append('lastModified',String(asset.lastModified??Date.now()));body.append('file',{uri:asset.uri,name:asset.name,type:asset.mimeType??'application/octet-stream'} as unknown as Blob);await call('/files/upload',{method:'POST',body});setMessage('원본 업로드 완료');await load()}catch(e){setMessage(e instanceof Error?e.message:'업로드 실패')}finally{setBusy(false)}};
  if(!token)return <SafeAreaView style={styles.login}><StatusBar style="dark"/><Text style={styles.brand}>ORIGINVAULT</Text><Text style={styles.title}>원본 그대로의{`\n`}개인 파일 금고</Text><TextInput style={styles.input} autoCapitalize="none" placeholder="아이디" value={username} onChangeText={setUsername}/><TextInput style={styles.input} secureTextEntry placeholder="비밀번호" value={password} onChangeText={setPassword}/>{message&&<Text style={styles.error}>{message}</Text>}<Pressable style={styles.primary} onPress={login} disabled={busy}><Text style={styles.primaryText}>{busy?'확인 중…':'로그인'}</Text></Pressable></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><StatusBar style="dark"/><View style={styles.header}><View><Text style={styles.kicker}>MY PRIVATE SPACE</Text><Text style={styles.heading}>내 파일</Text></View><Pressable style={styles.upload} onPress={upload}><Text style={styles.uploadText}>＋ 업로드</Text></Pressable></View><View style={styles.banner}><Text style={styles.bannerTitle}>✓ 원본 보존 모드</Text><Text style={styles.bannerText}>압축과 재인코딩 없이 안전하게 보관합니다.</Text></View>{busy&&<ActivityIndicator color="#2f6b4f"/>}{message&&<Text style={styles.message}>{message}</Text>}<FlatList data={files} keyExtractor={item=>item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>아직 보관한 파일이 없습니다.</Text>} renderItem={({item})=><View style={styles.card}><View style={styles.icon}><Text>▧</Text></View><View style={styles.fileText}><Text numberOfLines={1} style={styles.fileName}>{item.name}</Text><Text style={styles.meta}>{(Number(item.sizeBytes)/1024/1024).toFixed(1)} MB · SHA-256 검증</Text></View></View>}/></SafeAreaView>;
}

const styles=StyleSheet.create({login:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#f5f7f5'},brand:{color:'#2f6b4f',fontSize:12,fontWeight:'800',letterSpacing:3,marginBottom:25},title:{fontSize:36,fontWeight:'700',color:'#17201c',lineHeight:45,marginBottom:35},input:{height:52,backgroundColor:'#fff',borderWidth:1,borderColor:'#dfe5e1',borderRadius:12,paddingHorizontal:16,marginBottom:12},primary:{height:52,borderRadius:12,backgroundColor:'#2f6b4f',alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:'#fff',fontWeight:'700'},error:{color:'#a33b2d',marginVertical:8},screen:{flex:1,backgroundColor:'#f5f7f5'},header:{padding:24,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},kicker:{fontSize:10,color:'#2f6b4f',fontWeight:'800',letterSpacing:2},heading:{fontSize:31,fontWeight:'700',color:'#17201c'},upload:{backgroundColor:'#2f6b4f',borderRadius:10,paddingVertical:12,paddingHorizontal:15},uploadText:{color:'#fff',fontWeight:'700'},banner:{backgroundColor:'#e9f4ed',marginHorizontal:20,borderRadius:13,padding:16},bannerTitle:{color:'#2f6b4f',fontWeight:'700'},bannerText:{color:'#5c7567',fontSize:12,marginTop:4},message:{margin:20,color:'#2f6b4f'},list:{padding:20,gap:10},card:{backgroundColor:'#fff',borderRadius:13,padding:14,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#dfe5e1'},icon:{width:42,height:42,borderRadius:10,backgroundColor:'#edf3ef',alignItems:'center',justifyContent:'center'},fileText:{flex:1,marginLeft:12},fileName:{fontWeight:'600',color:'#17201c'},meta:{fontSize:11,color:'#69736e',marginTop:5},empty:{textAlign:'center',color:'#69736e',paddingTop:80}});
